# Generated by Django 3.2.4 on 2021-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='category',
            field=models.CharField(choices=[('CB', 'CELEBRITIES'), ('CY', 'COMPANY'), ('IF', 'INFLUENCERS'), ('EP', 'ENTREPRENEURS')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
