# Generated by Django 3.2.4 on 2021-06-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pageinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinfo',
            name='category',
            field=models.CharField(choices=[('CB', 'CELEBRITIES'), ('CY', 'COMPANY'), ('IF', 'INFLUENCERS'), ('EP', 'ENTREPRENEURS')], max_length=2, null=True),
        ),
    ]
