# Generated by Django 3.2.4 on 2021-06-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_pageinfo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='pages/profile-pic')),
                ('cover_pic', models.ImageField(upload_to='pages/cover-pic')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='users.page')),
            ],
        ),
    ]
