# Generated by Django 3.2.4 on 2021-06-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_pagephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CircleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(choices=[('CB', 'CELEBRITIES'), ('CY', 'COMPANY'), ('IF', 'INFLUENCERS'), ('EP', 'ENTREPRENEURS')], max_length=2, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('circle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='users.circle')),
            ],
        ),
        migrations.CreateModel(
            name='CirclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='circle/profile-pic')),
                ('cover_pic', models.ImageField(upload_to='circle/cover-pic')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('circle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='users.circle')),
            ],
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagephoto',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageInfo',
        ),
        migrations.DeleteModel(
            name='PagePhoto',
        ),
    ]
