# Generated by Django 3.2.4 on 2021-06-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
