# Generated by Django 3.2.4 on 2021-06-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_status_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='status/pictures'),
        ),
        migrations.AlterField(
            model_name='status',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
