# Generated by Django 3.2.4 on 2021-06-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_auto_20210623_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
