# Generated by Django 3.2.4 on 2021-06-23 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_auto_20210623_1244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circlefollower',
            unique_together={('user', 'circle')},
        ),
    ]
