# Generated by Django 3.2.4 on 2021-06-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_circlefollower_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='gossip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gossip_status', to='users.circle'),
        ),
    ]
