# Generated by Django 3.2.4 on 2021-06-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_status_gossip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='gossip',
        ),
    ]
