# Generated by Django 3.2.4 on 2021-07-08 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user1', 'user2')},
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
