# Generated by Django 3.2.4 on 2021-07-08 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_auto_20210709_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sent_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_by_user_requested', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created', '-id'],
                'unique_together': {('to_user', 'sent_by_user')},
            },
        ),
    ]
