# Generated by Django 3.2.4 on 2021-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_circle_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlephoto',
            name='cover_pic',
            field=models.ImageField(default='circle/cover-pic/default.jpg', upload_to='circle/cover-pic'),
        ),
        migrations.AlterField(
            model_name='circlephoto',
            name='profile_pic',
            field=models.ImageField(default='circle/profile-pic/default.jpg', upload_to='circle/profile-pic'),
        ),
    ]
