# Generated by Django 3.2.4 on 2021-07-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210717_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleinfo',
            name='category',
            field=models.CharField(choices=[('CB', 'CELEBRITIES'), ('CY', 'COMPANY'), ('IF', 'INFLUENCERS'), ('EP', 'ENTREPRENEURS')], default='CY', max_length=2, null=True),
        ),
    ]
