# Generated by Django 3.2.4 on 2021-07-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='martial_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
