# Generated by Django 3.2.4 on 2021-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210718_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='martial_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
