# Generated by Django 3.2.4 on 2021-06-25 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gossips', '0005_auto_20210620_0930'),
        ('controls', '0002_auto_20210617_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfrmodel',
            name='gossip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gossips.gossipsmodel'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfrmodel',
            name='reason',
            field=models.TextField(max_length=955),
        ),
        migrations.AlterUniqueTogether(
            name='rfrmodel',
            unique_together={('user', 'gossip')},
        ),
        migrations.RemoveField(
            model_name='rfrmodel',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='rfrmodel',
            name='post_title',
        ),
    ]
