# Generated by Django 3.0.8 on 2021-06-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resttoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
