# Generated by Django 3.2.4 on 2021-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resttoken_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resttoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
