# Generated by Django 3.0.8 on 2021-06-07 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatingroom',
            unique_together={('user1', 'user2')},
        ),
    ]
