# Generated by Django 3.2.4 on 2021-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20210617_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatingroommessage',
            options={'ordering': ['-date_created']},
        ),
    ]
