# Generated by Django 3.2.4 on 2021-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20210720_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
