# Generated by Django 3.2.4 on 2021-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_notifications_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('FR', 'FRIEND_REQUEST'), ('VT', 'VOTED_TRUE'), ('VF', 'VOTED_FALSE'), ('GC', 'GOSSIP_COMMENT'), ('CR', 'COMMENT_REPLY')], default='CR', max_length=2),
            preserve_default=False,
        ),
    ]
