# Generated by Django 3.0.8 on 2021-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gossipsmodel',
            name='link',
            field=models.CharField(blank=True, max_length=2040, null=True),
        ),
    ]
