# Generated by Django 3.2.4 on 2021-06-29 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gossips', '0005_auto_20210620_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gossipsmodel',
            name='false',
            field=models.ManyToManyField(related_name='false', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gossipsmodel',
            name='true',
            field=models.ManyToManyField(related_name='true', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VotedTrueToGossipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('gossip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voted_true', to='gossips.gossipsmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_voted_true', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotedFalseToGossipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('gossip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voted_false', to='gossips.gossipsmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_voted_false', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
