# Generated by Django 3.2.4 on 2021-06-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0007_auto_20210629_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votedfalsetogossipmodel',
            old_name='gossip',
            new_name='gossips_model',
        ),
        migrations.RenameField(
            model_name='votedtruetogossipmodel',
            old_name='gossip',
            new_name='gossips_model',
        ),
    ]
