# Generated by Django 3.2.4 on 2021-06-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0008_auto_20210629_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedtruetogossipmodel',
            name='gossips_model',
        ),
        migrations.RemoveField(
            model_name='votedtruetogossipmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='VotedFalseToGossipModel',
        ),
        migrations.DeleteModel(
            name='VotedTrueToGossipModel',
        ),
    ]
