# Generated by Django 3.2.4 on 2021-07-20 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gossips', '0009_auto_20210629_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='GossipObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('gossipsmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gossips.gossipsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gossipsmodel', 'user')},
            },
        ),
        migrations.AddField(
            model_name='gossipsmodel',
            name='objections',
            field=models.ManyToManyField(blank=True, related_name='user_objected', through='gossips.GossipObjection', to=settings.AUTH_USER_MODEL),
        ),
    ]
