# Generated by Django 3.0.8 on 2021-03-10 23:23

import cheaters.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is the title of your cheater story?', max_length=75, unique=True, verbose_name='Title')),
                ('content', models.TextField(max_length=3000)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('image', models.ImageField(blank=True, default='', help_text='Add image (optional)', null=True, upload_to=cheaters.models.upload_location)),
                ('shares', models.IntegerField(default=0)),
                ('from_question_user', models.CharField(blank=True, max_length=255, null=True)),
                ('from_question_answer_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheater_author', to=settings.AUTH_USER_MODEL)),
                ('false', models.ManyToManyField(blank=True, related_name='cheater_false', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cheaters',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, unique=True)),
                ('description', models.TextField(blank=True, help_text='You can optionally provide a description for this tag', max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheater_comment_author', to=settings.AUTH_USER_MODEL)),
                ('cheater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheaters.CheatersModel')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='cheatersmodel',
            name='q_tags',
            field=models.ManyToManyField(blank=True, to='cheaters.Tags'),
        ),
        migrations.AddField(
            model_name='cheatersmodel',
            name='true',
            field=models.ManyToManyField(blank=True, related_name='cheater_true', to=settings.AUTH_USER_MODEL),
        ),
    ]
